### ISSUE TITLE
Converting WOQL-JS to WOQL-JSON to WOQL-JS did not work: `SYNTAX ERROR: WOQL.decimal is not a function`

### ISSUE THREAD

**Issue by alexander-mart** [terminusdb/terminusdb-dashboard#305]
After toogle mode to `JSON` and back to `WOQL` and again to `JSON` (two times) with example query from docs i receive error: `WOQL.decimal is not a function`

**Doc page:**
https://terminusdb.com/docs/maths-based-queries-in-woql/

**How to reproduce:**

1. Paste example in WOQL-mode and run:
`SERVER ERROR: Not well formed WOQL JSON-LD`
```js
let v = Vars("result");
evaluate(times(2,3), v.result)
```

2. Convert to JSON:
```json
{
  "@type": "Eval",
  "expression": {
    "@type": "Times",
    "left": {
      "@type": "ArithmeticValue",
      "data": {
        "@type": "xsd:decimal",
        "@value": 2
      }
    },
    "right": {
      "@type": "ArithmeticValue",
      "data": {
        "@type": "xsd:decimal",
        "@value": 3
      }
    }
  },
  "result": {
    "@type": "ArithmeticValue",
    "variable": "result"
  }
}
```

3. Convert to WOQL:
```js
WOQL.eval(WOQL.times({"@type":"xsd:decimal","@value":2}, {"@type":"xsd:decimal","@value":3}), "v:result")
```

4. Convert to JSON:
```json
{
  "@type": "Eval",
  "expression": {
    "@type": "Times",
    "left": {
      "@type": "xsd:decimal",
      "@value": 2
    },
    "right": {
      "@type": "xsd:decimal",
      "@value": 3
    }
  },
  "result": {
    "@type": "ArithmeticValue",
    "variable": "result"
  }
}
```

4. Convert to WOQL:
```js
WOQL.eval(WOQL.times(WOQL.decimal(2), WOQL.decimal(3)), "v:result")
```

5. Convert to JSON:
:x: `SYNTAX ERROR: WOQL.decimal is not a function`

**Comment by alexander-mart** [comment]
From [Discord](https://discord.com/channels/689805612053168129/689886415491825703/1179444566877810768):

> LaurentS:
> We tried replacing `xsd:decimal` with its equivalent (according to the docs) `xsd:double` but it didn't help.

**Comment by alexander-mart** [comment]
Examples from the documentation still don't work a month later:
https://terminusdb.com/docs/maths-based-queries-in-woql/

The error changed from `SERVER ERROR: Not well formed WOQL JSON-LD` to:
`SERVER ERROR: The query you have sent has no viable mode. Some variables can not be bound under any reordering.`

```js
let v = Vars("result");
evaluate(times(2,3), v.result)
```

or this:
```js
evaluate(times(2,3), "v:result")
```

**Comment by alexander-mart** [comment]
@GavinMendelGleason Give me a hint where to look at the code that is responsible for this? I'll try to find a bug or missing method

**Comment by alexander-mart** [comment]
Related issue about unable to using math methods: https://github.com/terminusdb/terminusdb/issues/2076

**Comment by alexander-mart** [comment]
It's working in [v11.1.14](https://github.com/terminusdb/terminusdb-dashboard/issues/305)
